server:
  port: 5555

spring:
  application:
    name: gateway

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  cloud:
    gateway:
      routes:
        - id: membership
          predicates:
            - Path=/users/**
          uri: lb://MEMBERSHIP-SERVICE
          sensitive-headers: Cookie,Set-Cookie
        - id: post
          predicates:
            - Path=/posts/**
          uri: lb://POST-SERVICE
          sensitive-headers: Cookie,Set-Cookie
        - id: feed
          predicates:
            - Path=/feed/**
          uri: lb://FEED-SERVICE
          sensitive-headers: Cookie,Set-Cookie
        - id: follow
          predicates:
            - Path=/follow/**
          uri: lb://FOLLOW-SERVICE
          sensitive-headers: Cookie,Set-Cookie

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 600000

  security:
    basic:
      enable: false

    jwt:
      secret: happilyeverafterhappilyeverafter