server:
  port: 8010

spring:
  application:
    name: membership-service

  datasource:
    url: jdbc:mysql://localhost:3306/instagram?characterEncoding=UTF-8&serverTimezone=UTC
    username: users
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

  security:
    basic:
      enable: false

  jwt:
    secret: happilyeverafterhappilyeverafter

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher